export const SELECTION_RADIUS = 8
export const WORLD_BOUNDS = 30
export const GRID_SIZE = 1
export const CASTLE_RADIUS = 0.5
export const PLAYER_SPEED = 6
export const MOB_SPEED = 3
export const NPC_SPEED = 4
export const SHOOT_COOLDOWN = 0.5
export const SHOOT_DAMAGE = 5
export const TOWER_HEIGHT = 2
export const WALL_HP = 100
export const TOWER_HP = 10
export const MOB_SIEGE_DAMAGE = 2
export const MOB_SIEGE_ATTACK_COOLDOWN = 0.8
export const MOB_SIEGE_RANGE_BUFFER = 0.35
export const MOB_SIEGE_UNREACHABLE_GRACE = 1.2
export const WALL_CHARGE_MAX = 200
export const TOWER_CHARGE_MAX = 50
export const CHARGE_FULL_RECHARGE_TIME = 60
export const WALL_RECHARGE_RATE = WALL_CHARGE_MAX / CHARGE_FULL_RECHARGE_TIME
export const TOWER_RECHARGE_RATE = TOWER_CHARGE_MAX / CHARGE_FULL_RECHARGE_TIME
export const FLOW_FIELD_RESOLUTION = GRID_SIZE
export const FLOW_FIELD_SIZE = Math.ceil((WORLD_BOUNDS * 2) / FLOW_FIELD_RESOLUTION)
export const SPATIAL_GRID_CELL_SIZE = 3
