export const ENABLE_PROJECTILE_BROADPHASE = true;
export const ENABLE_INCREMENTAL_SPATIAL_GRID = true;
export const ENABLE_MOB_RENDER_LOD = true;
export const MOB_LOD_NEAR_DISTANCE = 25;
export const MOB_LOD_FAR_DISTANCE = 48;
export const MOB_LOD_MID_ANIMATION_STEP_MS = 33;
export const MOB_LOD_FAR_ANIMATION_STEP_MS = 90;
export const MOB_LOD_DISABLE_FAR_WIGGLE = true;
export const TOWER_TARGET_REFRESH_INTERVAL_FRAMES = 2;
export const STAGING_ISLAND_DISTANCE = 14;
export const STAGING_ISLAND_SIZE = 15;
export const STAGING_ISLAND_HEIGHT = 1;
export const STAGING_BRIDGE_SIDE_GROUND_ROWS = 1;
export const STAGING_BRIDGE_PATH_WIDTH = 3;
export const STAGING_BRIDGE_WIDTH =
  STAGING_BRIDGE_PATH_WIDTH + STAGING_BRIDGE_SIDE_GROUND_ROWS * 2;
export const STAGING_BRIDGE_LENGTH = 11;
export const SPAWNER_ENTRY_INSET_CELLS = 3;
export const STAGING_PLATFORM_Y = Math.max(0, STAGING_ISLAND_HEIGHT - 1);
export const MOB_STAGING_BOUNDS_PADDING =
  STAGING_ISLAND_DISTANCE + STAGING_ISLAND_SIZE * 0.5 + 2;

export const CASTLE_ROUTE_HALF_WIDTH_CELLS = Math.max(
  0,
  Math.floor(STAGING_BRIDGE_PATH_WIDTH * 0.5)
);
export const CASTLE_ENTRY_GOAL_STRIP_HALF_WIDTH_CELLS =
  CASTLE_ROUTE_HALF_WIDTH_CELLS;

export const COIN_PILE_CYLINDER_MIN = 3;
export const COIN_PILE_CYLINDER_MAX = 96;
export const COIN_PILE_MAX_RADIUS = 2.1;
export const COIN_PILE_CLUSTER_MAX_PER_CORNER = 5;

export const EVENT_BANNER_DURATION = 2.4;

export const HITBOX_LAYER = 1;
export const PATHLINE_REFRESH_BUDGET_PER_FRAME = 2;

export const RESYNC_COOLDOWN_MS = 15_000;
export const SERVER_MOB_INTERPOLATION_BACKTIME_MS = 150;
export const SERVER_MOB_EXTRAPOLATION_MAX_MS = 900;
export const SERVER_MOB_EXTRAPOLATION_GAP_MAX_MS = 8_000;
export const SERVER_MOB_DEAD_STALE_REMOVE_MS = 1000;
export const SERVER_MOB_ACTIVE_WAVE_STALE_REMOVE_MS = 8000;
export const SERVER_MOB_POST_WAVE_STALE_REMOVE_MS = 4000;
export const SERVER_MOB_HARD_STALE_REMOVE_MS = 15000;
export const SERVER_HEARTBEAT_INTERVAL_MS = 500;
export const SERVER_STRUCTURE_SYNC_INTERVAL_MS = 30_000;
export const SERVER_STRUCTURE_SYNC_RETRY_MS = 7_500;
export const SNAPSHOT_STRUCTURE_GRACE_MS = 3_000;
export const SERVER_META_SYNC_INTERVAL_MS = 10_000;
export const SERVER_META_SYNC_RETRY_MS = 3_000;
export const MOVE_INTENT_MIN_INTERVAL_MS = 100;
