export const ENABLE_PROJECTILE_BROADPHASE = true;
export const ENABLE_INCREMENTAL_SPATIAL_GRID = true;
export const ENABLE_MOB_RENDER_LOD = true;
export const MOB_LOD_NEAR_DISTANCE = 25;
export const MOB_LOD_FAR_DISTANCE = 48;
export const MOB_LOD_MID_ANIMATION_STEP_MS = 33;
export const MOB_LOD_FAR_ANIMATION_STEP_MS = 90;
export const MOB_LOD_DISABLE_FAR_WIGGLE = true;
export const TOWER_TARGET_REFRESH_INTERVAL_FRAMES = 2;
export const STAGING_ISLAND_DISTANCE = 14;
export const STAGING_ISLAND_SIZE = 15;
export const STAGING_ISLAND_HEIGHT = 1;
export const STAGING_BRIDGE_SIDE_GROUND_ROWS = 1;
export const STAGING_BRIDGE_PATH_WIDTH = 3;
export const STAGING_BRIDGE_WIDTH =
  STAGING_BRIDGE_PATH_WIDTH + STAGING_BRIDGE_SIDE_GROUND_ROWS * 2;
export const STAGING_BRIDGE_LENGTH = 11;
export const SPAWNER_ENTRY_INSET_CELLS = 3;
export const STAGING_PLATFORM_Y = Math.max(0, STAGING_ISLAND_HEIGHT - 1);
export const MOB_STAGING_BOUNDS_PADDING =
  STAGING_ISLAND_DISTANCE + STAGING_ISLAND_SIZE * 0.5 + 2;

export const CASTLE_ROUTE_HALF_WIDTH_CELLS = Math.max(
  0,
  Math.floor(STAGING_BRIDGE_PATH_WIDTH * 0.5)
);
export const CASTLE_ENTRY_GOAL_STRIP_HALF_WIDTH_CELLS =
  CASTLE_ROUTE_HALF_WIDTH_CELLS;

export const COIN_PILE_CYLINDER_MIN = 3;
export const COIN_PILE_CYLINDER_MAX = 96;
export const COIN_PILE_MAX_RADIUS = 2.1;
export const COIN_PILE_CLUSTER_MAX_PER_CORNER = 5;

export const EVENT_BANNER_DURATION = 2.4;
