export const SIM_TICK_MS = 100;
export const MAX_MOBS = 10_000;
export const MAX_DELTA_PLAYERS = 200;
export const MAX_DELTA_MOBS = 200;
export const MAX_STRUCTURE_DELTA_UPSERTS = 100;
export const MAX_STRUCTURE_DELTA_REMOVES = 100;

export const ENABLE_FULL_MOB_DELTAS = true;
export const FULL_MOB_DELTA_INTERVAL_MS = 5_000;
export const FULL_MOB_DELTA_ON_STRUCTURE_CHANGE_WINDOW_MS = 1_000;
export const FULL_MOB_SNAPSHOT_CHUNK_SIZE = 600;
export const DELTA_NEAR_MOBS_BUDGET = 220;
export const DELTA_CASTLE_THREAT_MOBS_BUDGET = 160;
export const DELTA_RECENTLY_DAMAGED_MOBS_BUDGET = 120;
export const ENABLE_INTEREST_MANAGED_MOB_DELTAS = true;
export const ENABLE_SERVER_TOWER_SPATIAL_DAMAGE = true;

export const AUTO_WAVE_INITIAL_DELAY_MS = 5_000;
export const AUTO_WAVE_INTERMISSION_MS = 10_000;
