export {
  runSimulation,
  buildPresenceLeaveDelta,
  type SimulationResult,
  type SimulationPerfStats,
} from './simulation';

export {
  SIM_TICK_MS,
  MAX_MOBS,
  MAX_DELTA_PLAYERS,
  MAX_DELTA_MOBS,
  MAX_STRUCTURE_DELTA_UPSERTS,
  MAX_STRUCTURE_DELTA_REMOVES,
  ENABLE_FULL_MOB_DELTAS,
  FULL_MOB_DELTA_INTERVAL_MS,
  FULL_MOB_DELTA_ON_STRUCTURE_CHANGE_WINDOW_MS,
  FULL_MOB_SNAPSHOT_CHUNK_SIZE,
  DELTA_NEAR_MOBS_BUDGET,
  DELTA_CASTLE_THREAT_MOBS_BUDGET,
  DELTA_RECENTLY_DAMAGED_MOBS_BUDGET,
  ENABLE_INTEREST_MANAGED_MOB_DELTAS,
  ENABLE_SERVER_TOWER_SPATIAL_DAMAGE,
  AUTO_WAVE_INITIAL_DELAY_MS,
  AUTO_WAVE_INTERMISSION_MS,
} from './config';
